# Generated by Django 4.2.5 on 2023-09-18 16:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reg_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtmodel',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_photosessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
