# Generated by Django 4.2.5 on 2023-11-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_form', '0003_discount_dtmodel_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtmodel',
            name='session_type',
            field=models.CharField(choices=[('Wedding', 'Wedding photo session'), ('Pet', 'Pet photo session'), ('Love', 'Love story'), ('Studio', 'Studio photo session')], default='standard', max_length=10),
        ),
    ]
