# Generated by Django 4.2.5 on 2023-11-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_form', '0003_discount_dtmodel_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtmodel',
            name='editable',
            field=models.BooleanField(default=False),
        ),
    ]
