# Generated by Django 4.2.5 on 2023-11-24 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('wedding', 'Свадебные'), ('animal', 'Анималистические'), ('love_story', 'Лавстори'), ('studio', 'Студийные')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/images')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.photo')),
            ],
        ),
    ]
