# Generated by Django 4.2.5 on 2023-11-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='photos/')),
                ('category', models.CharField(choices=[('wedding', 'Свадебные'), ('animal', 'Анималистические'), ('love_story', 'Лавстори'), ('studio', 'Студийные')], max_length=20)),
            ],
        ),
    ]
