# Generated by Django 4.2.4 on 2023-08-23 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='image',
            new_name='photo',
        ),
    ]
