# Generated by Django 4.2.4 on 2023-09-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_rename_photo_skill_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='price_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
